version: "3.9"
services:
  discovery:

    build:  ../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - logging.level.com.netflix.eureka=DEBUG

  gateway:
      build: ../apigateway
      ports:
        - "8181:8181"
      image: "api-gateway"
      environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
        - eureka.instance.preferIpAddress=true
        - logging.level.com.netflix.eureka=DEBUG
      depends_on:
        - discovery

  event:
    build: ../eventservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - logging.level.com.netflix.eureka=DEBUG
    ports:
      - "8089:8089"
    image: "eventt-service"
    depends_on:
      - discovery
      - gateway

  joueur:
    build: ../employeeservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - logging.level.com.netflix.eureka=DEBUG
    ports:
      - "8093:8093"
    image: "joueur-service"
    depends_on:
      - discovery
      - mysqldb1
      - gateway
  mysqldb1:
      image: "mysql:5.7"
      ports:
        - "3306:3306"
      environment:
        - spring.datasource.username=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=emp

